# Generated by Django 6.0.5 on 2026-06-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_motivation_and_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='email',
        ),
        migrations.AddField(
            model_name='invitation',
            name='note',
            field=models.CharField(blank=True, help_text="Optional internal label, e.g. 'for John from Twitter'.", max_length=120),
        ),
    ]
